version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meteorological-api
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/files
    environment:
      - PYTHONUNBUFFERED=1
